.github/pull_request_template.md
README.md
publishing/release-rules.cjs

Due to rules being a glob, the `!` marker was treated as a negation and accidentally treated all minor version bumps as major. This removes that possibility!

chore(release): fix breaking change marker

---

.github/workflows/push-branches-from-main.yaml
.github/workflows/semantic-release.yaml
sdks/uniswapx-sdk/package.json

- Automatically publishes on push to main or beta based on commit messages (PR scope/titles)
- Pushes to beta, not alpha as alpha has issues properly keeping up its version
- Updates `uniswapx-sdk` to publish as beta

chore(release): autopublishing from main and beta + uniswapx-sdk to beta

---

sdks/uniswapx-sdk/integration/package.json
sdks/uniswapx-sdk/package.json
sdks/v2-sdk/package.json
sdks/v3-sdk/package.json
yarn.lock

Updates the SDK core dependency (needed due to the unintentional major version bump, non-breaking)
- testing done on https://github.com/Uniswap/sdks/pull/11
This will be done in `router-sdk` and then `universal-router-sdk` once each step has been published

fix(v2-sdk, v3-sdk, uniswapx-sdk): update sdk-core dependency version

---

.github/workflows/monorepo-integrity.yml
sdks/universal-router-sdk/package.json
yarn.lock

PR 3/3 from #18
Completes the update of sdk-core version across all packages!
Same as #18

fix(universal-router-sdk): update sdk-core dependency version

---

sdks/universal-router-sdk/package.json
yarn.lock

fix(universal-router-sdk): bump sdk core to support zksync weth

---

.github/workflows/semantic-release.yaml

Updates the npm token and sets it to use the runner. When this gets merged I need to rotate the vault token (takes 30 seconds)

chore(infra): sets up the npm deploy job to use the github runner

---

sdks/router-sdk/src/entities/trade.test.ts
sdks/router-sdk/src/entities/trade.ts
sdks/router-sdk/src/swapRouter.test.ts

make it so v4 routes don't introduce breaking changes without a major upgrade.
fixes: https://github.com/Uniswap/sdks/issues/80

feat(router-sdk): undo breaking changes when adding v4 routes

---

.github/workflows/trufflehog.yml

Simply make trufflehog only run on the PR stage

chore(infra): don't run trufflehog on main

---

sdks/v3-sdk/src/constants.ts

Adding 3 more fee tiers in `FeeAmount` enum 
This is needed for SOR routing updates.
Based on offline discussions, this addition of new tiers shouldn't affect anything.
Please let me know if there is any concern for adding those new fee tiers here.

feat(v3-sdk): Adding extra fee tiers for V3

---

sdks/universal-router-sdk/src/utils/constants.ts

Update universal router v2_1 sepolia address
This will unblock https://github.com/Uniswap/smart-order-router/pull/728 failed sepolia test
No
We will need to deploy universal router to production nets

fix(universal-router-sdk): update universal router v2_1 sepolia address

---

sdks/v3-sdk/src/nonfungiblePositionManager.test.ts
sdks/v3-sdk/src/nonfungiblePositionManager.ts
sdks/v4-sdk/src/PositionManager.test.ts
sdks/v4-sdk/src/PositionManager.ts

This commit adds helper functions for building the domains, types,
values of permits for v3 and v4 NFTs
If there are breaking changes, please ensure you …

feat(v3/v4-sdk): add Permit building

---

sdks/v2-sdk/package.json
yarn.lock

Bump sdk-core in v2-sdk. This is needed because v2-sdk [FACTORY_ADDRESS_MAP](https://github.com/Uniswap/sdks/blob/main/sdks/v2-sdk/src/constants.ts#L9) uses V2_FACTORY_ADDRESSES from sdk-core
No

feat(v2-sdk): bump sdk-core to have v2-sdk factory address on worldchain

---

sdks/router-sdk/package.json
yarn.lock

bump sdk-core,v2-sdk,v3-sdk in router-sdk for worldchain weth9. router-sdk has [weth9](https://github.com/search?q=repo%3AUniswap%2Fsdks+weth9+path%3A%2F%5Esdks%5C%2Frouter-sdk%5C%2Fsrc%5C%2F%2F&type=code), so it needs from sdk-core 
No

feat(router-sdk): bump sdk-core,v2-sdk,v3-sdk in router-sdk for worldchain weth9

---

sdks/v2-sdk/package.json
yarn.lock

v2-sdk needs sdk-core v2 factory address
No

feat(v2-sdk): bump sdk-core to have v2-sdk factory address on astrochain sepolia

---

sdks/sdk-core/src/addresses.ts

WorldChain and astrochain sepolia are missing SwapV2Router02 addresses, they were already deployed.
Astrochain sepolia had the v3 deployed with wrong v3 factory addresses in quoter, v3 migrator, nft position manager and swaprouter02, hence re-deployed and updating contract addresses here
No

fix(sdk-core): update some worldchain and astrochain sepolia contract addresses

---

sdks/v2-sdk/package.json
yarn.lock

bump sdk-core in v2-sdk for astrochain v3 redeploy
will test in routing

fix(v2-sdk): bump sdk-core in v2-sdk for astrochain v3 redeploy

---

sdks/universal-router-sdk/src/index.ts
sdks/universal-router-sdk/src/utils/commandParser.ts

This commit refactors the parser to allow injection of arbitrary
commands definitions. This enables supporting old UR command sets
If there are breaking …

feat(ur-sdk): allow commands override

---

sdks/sdk-core/src/addresses.ts
sdks/sdk-core/src/entities/weth9.ts

we have deployed v4 to sepolia and astrochain sepolia. for v4, we are missing state view and quoter addresses, hence adding in sepolia. astrochain sepolia was more recently deployed with v4, so adding there as well.
sepolia 11155111 weth9 is good to be added, although based on the chat with @zhongeric , it should only be used in [SwapRouter02.sol](https://github.com/Uniswap/swap-router-contracts/blob/main/contracts/SwapRouter02.sol), which is deprecated in favor in Universal Router. in Uniswap frontend and Uniswap backend, we do not submit calldata to SwapRouter02.sol, only to Universal Router
No
No
No
No

fix(sdk-core): add v4Quoter, stateView, viewQuoterV3, add sepolia weth9

---

sdks/v3-sdk/src/multicall.test.ts
sdks/v3-sdk/src/multicall.ts

Adds a decode function to multicall to help migrator work
If there are breaking changes, please ensure you bump the major version Bump the major version …

feat(v3-sdk): add decode to multicall

---

sdks/universal-router-sdk/src/utils/constants.ts

protocol team plans to re-deploy v4 to sepolia tomorrow. UR v2.0 has to be re-deployed as well.
will test from test web UI.
No

fix(universal-router-sdk): update UR address in sepolia once v4 re-deployed

---

sdks/v2-sdk/package.json
yarn.lock

Bump sdk-core in v2-sdk. This is needed because v2-sdk [FACTORY_ADDRESS_MAP](https://github.com/Uniswap/sdks/blob/main/sdks/v2-sdk/src/constants.ts#L9) uses V2_FACTORY_ADDRESSES from sdk-core
Not really - besides new sdk-core renamed `Chain.ASTROCHAIN_SEPOLIA` TO `Chain.UNICHAIN_SEPOLIA`

feat(v2-sdk): bump sdk-core to have v2-sdk factory address for Unichain

---

sdks/v3-sdk/package.json
yarn.lock

Bump sdk-core in v3-sdk. v3-sdk uses ChainId enum from sdk-core https://github.com/search?q=repo%3AUniswap%2Fsdks+sdk-core+path%3A%2F%5Esdks%5C%2Fv3-sdk%5C%2F%2F&type=code, so v3-sdk needs Unichain chain id
Not really - besides new sdk-core renamed `Chain.ASTROCHAIN_SEPOLIA` to `Chain.UNICHAIN_SEPOLIA`

feat(v3-sdk): bump sdk-core to have Unichain chainId

---

sdks/uniswapx-sdk/src/utils/order.test.ts

Addressing a gap in tests for using the Order Parser on unsigned & cosigned DutchV3 orders
Labelled as fix to trigger npm patch release with latest commits

fix(uniswapx-sdk): DutchV3 order parsing

---

.github/workflows/monorepo-integrity.yml
sdks/v4-sdk/package.json
yarn.lock

Need to bump `v3-sdk`, `sdk-core` before bumping `router-sdk` in [this PR](https://github.com/Uniswap/sdks/pull/202) otherwise build complains.
temporarily disabling `yarn dedupe --check`  as there are some dependency issues between router-sdk and v4-sdk. Will re-enable in this [router-sdk PR](https://github.com/Uniswap/sdks/pull/202)
No AFAIK

feat(v4-sdk): bump sdk-core, v3-sdk for syncd Unichain support in router-sdk

---

sdks/router-sdk/package.json
yarn.lock

bump sdk-core,v2-sdk,v3-sdk,v4-sdk in router-sdk for unichain weth9. router-sdk has [weth9](https://github.com/search?q=repo%3AUniswap%2Fsdks+weth9+path%3A%2F%5Esdks%5C%2Frouter-sdk%5C%2Fsrc%5C%2F%2F&type=code), so it needs it from sdk-core 
No

feat(router-sdk): bump sdk-core,v2-sdk,v3-sdk,v4-sdk in router-sdk for unichain weth9

---

sdks/sdk-core/src/addresses.ts
sdks/sdk-core/src/chains.ts

Adds Monad Testnet.
Unblocks review on https://github.com/Uniswap/universe/pull/14305
Linked to local repo and ensure everything runs as expected
No
If there are breaking changes, please ensure you bump …

feat(sdk-core): add monad testnet

---

sdks/v2-sdk/.eslintrc.json
sdks/v2-sdk/jest.config.js
sdks/v2-sdk/package.json
sdks/v2-sdk/tsconfig.base.json
sdks/v2-sdk/tsconfig.cjs.json
sdks/v2-sdk/tsconfig.esm.json
sdks/v2-sdk/tsconfig.types.json
yarn.lock

breaking change to build structure for `v2-sdk`
updates the build setup for `v2-sdk` to manually and explicitly create separate cjs and esm builds (plus a types-only version)
built the sdk locally, then installed the local build result in another project (`universe/apps/web`) and verified that it properly resolved the esm version instead of the cjs version
there shouldn't be, but technically if an end user is importing incorrectly (by directly referencing any build artifact files) then they'll need to update
PRs to follow will do this for many other SDKs

feat(v2-sdk): separate esm/cjs builds

---

sdks/sdk-core/src/addresses.ts

Re-deployed v4.
No, but this address only works with v4-sdk @uniswap/v4-sdk-v1.12.3+

fix(sdk-core): update v4 testnets addresses

---

sdks/uniswapx-sdk/.eslintrc.json
sdks/uniswapx-sdk/integration/package.json
sdks/uniswapx-sdk/integration/test/PriorityOrder.spec.ts
sdks/uniswapx-sdk/integration/test/PriorityOrderValidator.spec.ts
sdks/uniswapx-sdk/integration/test/RelayOrderValidator.spec.ts
sdks/uniswapx-sdk/integration/test/V3DutchOrder.spec.ts
sdks/uniswapx-sdk/jest.config.js
sdks/uniswapx-sdk/package.json
sdks/uniswapx-sdk/tsconfig.base.json
sdks/uniswapx-sdk/tsconfig.cjs.json
sdks/uniswapx-sdk/tsconfig.esm.json
sdks/uniswapx-sdk/tsconfig.types.json
turbo.json
yarn.lock

breaking change to build structure for `uniswapx-sdk`
updates the build setup for `uniswapx-sdk` to manually and explicitly create separate cjs and esm builds (plus a types-only version)
built the sdk locally, then installed the local build result in another project (`universe/apps/web`) and verified that it properly resolved the esm version instead of the cjs version
there shouldn't be, but technically if an end user is importing incorrectly (by directly referencing the `uniswapx-sdk.esm.js` file) then they'll need to update
PRs to follow will do this for many other SDKs

feat(breaking): esm/cjs builds for uniswapx-sdk

---

sdks/sdk-core/src/chains.ts

Updates chain ID for Monad Testnet
Linked to universe repo to verify the package resolves correctly, but e2e testing is blocked pending other changes.
Unsure (will verify)
_[e.g. Type definitions, …

fix(sdk-core): update chain ID for Monad Testnet

---

sdks/v3-sdk/package.json
yarn.lock

feat(v3-sdk): bump sdk-core to 7.1.0 for base sepolia and monad testnet in v3-sdk

---

sdks/v2-sdk/package.json
yarn.lock

Release https://github.com/Uniswap/sdks/pull/240 https://github.com/Uniswap/sdks/pull/228

feat(v2-sdk): bump sdk-core to 7.1.0 for base sepolia and monad testnet

---

sdks/v4-sdk/package.json
yarn.lock

Release https://github.com/Uniswap/sdks/pull/242 https://github.com/Uniswap/sdks/pull/240

feat(v4-sdk): bump sdk-core to 7.1.0 for base sepolia and monad testnet in v4-sdk

---

.github/workflows/monorepo-integrity.yml
sdks/router-sdk/package.json
yarn.lock

Release https://github.com/Uniswap/sdks/pull/243 https://github.com/Uniswap/sdks/pull/241 https://github.com/Uniswap/sdks/pull/242

feat(router-sdk): bump sdk-core to 7.1.0 for base sepolia and monad testnet in router-sdk

---

sdks/v3-sdk/package.json
yarn.lock

Release https://github.com/Uniswap/sdks/pull/249

feat(v3-sdk): bump sdk-core to 7.2.0 for arb, base, polygon

---

sdks/router-sdk/package.json
sdks/universal-router-sdk/test/utils/commandParser.test.ts
yarn.lock

Release https://github.com/Uniswap/sdks/pull/252 https://github.com/Uniswap/sdks/pull/251 https://github.com/Uniswap/sdks/pull/250 https://github.com/Uniswap/sdks/pull/249

feat(router-sdk): bump sdk-core to 7.2.0 for arb, base, polygon

---

sdks/v2-sdk/package.json
yarn.lock

Release https://github.com/Uniswap/sdks/pull/257

feat(v2-sdk): bump sdk-core to 7.3.0 for bnb op avax world

---

sdks/router-sdk/package.json
yarn.lock

Release #257 #260  https://github.com/Uniswap/sdks/pull/261

feat(router-sdk): bump sdk-core to 7.3.0 for bnb op avax world

---

sdks/universal-router-sdk/test/utils/commandParser.test.ts

chore(universal-router-sdk): Remove sqrtPrice from UR SDK v4 single

---

.github/CODEOWNERS

chore(sdks): add routing-team into codeowner

---

sdks/uniswapx-sdk/src/utils/index.ts

Add missing PermissionedTokenValidator export in utils.

fix(uniswapx-sdk): Add missing export

---

sdks/smart-wallet-sdk/package.json

ignore the rule where the typescript dependency has to match the typescript version of the other repos
https://github.com/Thinkmill/manypkg?tab=readme-ov-file#ignoring-this-rule
__________________
This pull request includes a small change to the `sdks/smart-wallet-sdk/package.json` file. The change updates the `typescript` dependency to use npm aliasing. 
* [`sdks/smart-wallet-sdk/package.json`](diffhunk://#diff-6c97d321754bade5fb6134807a3992e56311a86f9d28b0ca7d9739e86d2c805cL54-R54): Updated the `typescript` dependency to use npm aliasing (`npm:typescript@^5.6.2`).

Dependency CI fix for 

---

sdks/router-sdk/package.json
sdks/sdk-core/package.json
sdks/v2-sdk/package.json
sdks/v3-sdk/package.json
sdks/v4-sdk/package.json

fixes the release scripts for v2, v3, v4 and sdk-core
recent changes to the build processes in these SDKs accidentally removed the yarn script for running semantic release. this adds it back for the listed SDKs
test by looking and verifying it releases when merged
no

fix: re-add release scripts

---

sdks/universal-router-sdk/src/index.ts

need to export [Permit2Permit](https://github.com/Uniswap/sdks/blob/35a3e02f4ba39b31c6ac421fca9a83bc7bf15ed8/sdks/universal-router-sdk/src/utils/inputTokens.ts#L9) as index from ur-sdk, because of SOR [dist import style](https://github.com/Uniswap/smart-order-router/blob/e635eba43055265b1ae3c7450f79729588b5399a/test/integ/routers/alpha-router/alpha-router.integration.test.ts#L29).
will test in SOR
No

fix(universal-router-sdk): export Permit2Permit

---

sdks/uniswapx-sdk/src/trade/V3DutchOrderTrade.test.ts
sdks/uniswapx-sdk/src/trade/V3DutchOrderTrade.ts

Similar to Priority Trades, allow caller to pass in the expected amounts to the trade to override the amount in/out.
Unit tests
No.

feat(UniswapX): Add expected amounts to DutchV3

---

sdks/smart-wallet-sdk/src/constants.test.ts
sdks/smart-wallet-sdk/src/constants.ts

fix(smart-wallet-sdk): add historical smart wallet versions

---

sdks/uniswapx-sdk/integration/test/V3DutchOrder.spec.ts

The second signer in `ethers.getSigners()` has been delegated somehow and is breaking our tests because we haven't updated hardhat. This is a quick fix

fix(uniswapx-sdk): Use different default signer in integration tests

---

sdks/smart-wallet-sdk/README.md
sdks/smart-wallet-sdk/src/constants.ts

Adds newest deploys (v1_0_0) for the following chains:
```
export enum SupportedChainIds {
MAINNET = ChainId.MAINNET,
UNICHAIN = ChainId.UNICHAIN,
UNICHAIN_SEPOLIA = ChainId.UNICHAIN_SEPOLIA,
SEPOLIA = ChainId.SEPOLIA,
BASE = ChainId.BASE,
OPTIMISM = ChainId.OPTIMISM,
BNB = ChainId.BNB,
}
```
All other chains are not supported for the v1 launch and removed.

fix(smart-walet-sdk): V1 launch addresses and README

---

sdks/uniswapx-sdk/integration/test/PermissionedTokenValidatorLive.spec.ts
sdks/uniswapx-sdk/src/constants.ts

After testing `0x7712c34205737192402172409a8F7ccef8aA2AEc` with a real permissioned address, I can see that the proxy isn't necessary.
Integration test (included).

fix(uniswapx-sdk): Fix proxy type

---

sdks/smart-wallet-sdk/src/constants.ts
sdks/smart-wallet-sdk/src/smartWallet.test.ts
sdks/smart-wallet-sdk/src/smartWallet.ts

Hardened `SmartWallet.createExecute` against prototype pollution and invalid inputs; hardened the address map; added tests. This addresses a reported issue where passing inherited object keys like `"__proto__"` or `"constructor"` as `chainId` would incorrectly pass the existing check, producing malformed `to` addresses. Reported via [Cantina Finding #471](https://cantina.xyz/code/f9df94db-c7b1-434b-bb06-d1360abdd1be/findings?finding=471)
- **Input validation** (`src/smart-wallet-sdk/src/smartWallet.ts`)
- Normalize `chainId` (convert string to number when possible).
- Validate it is a finite integer and a direct key of `SMART_WALLET_ADDRESSES` using `Object.prototype.hasOwnProperty.call`.
- If invalid or absent, throw: `Smart wallet not found for chainId: ${chainId}`.
- **Map hardening** …

fix(smart-wallet-sdk): harden `createExecute` against prototype pollution attacks
