- .github/pull_request_template.md
Adding a reminder to the PR template to notify the #eng-sdk channel for breaking changes.
> chore(docs): Add reminder about breaking changes

- .github/pull_request_template.md
Updates the examples of PR titles to cover the chore case!
> chore(docs): Clarify title options for non-release PR's

- .github/workflows/monorepo-integrity.yml
- sdks/router-sdk/package.json
- sdks/universal-router-sdk/package.json
- yarn.lock
PR 2/3 from #18
Same as #18
Once published, we will update in `universal-router-sdk` for the final PR
> fix(router-sdk): update sdk-core dependency version

- sdks/uniswapx-sdk/src/constants.test.ts
- sdks/uniswapx-sdk/src/constants.ts
- sdks/uniswapx-sdk/src/utils/order.test.ts
> feat(uniswapx-sdk): update reactor address

- sdks/sdk-core/src/entities/weth9.ts
> fix(sdk-core): add weth9 for zksync

- sdks/router-sdk/package.json
- yarn.lock
> fix(router-sdk): bump sdk core version to 5.3.1

- sdks/v2-sdk/package.json
- sdks/v3-sdk/package.json
- yarn.lock
> fix(v2-sdk): bump sdk core to 5.3.1

- sdks/v3-sdk/package.json
- yarn.lock
> fix(v3-sdk): bump sdk-core to 5.3.1

- sdks/universal-router-sdk/package.json
- yarn.lock
> fix(universal-router-sdk): bump V2,V3,router sdks

- sdks/uniswapx-sdk/src/utils/order.test.ts
- sdks/uniswapx-sdk/src/utils/order.ts
Implement parseOrder and getOrderType for priority orders and add tests
If there are breaking changes, please ensure you bump the major version Bump the major version (by using the title `feat(breaking): …
> fix(uniswapx-sdk): add priority order parsing and tests

- .github/workflows/semantic-release.yaml
Allows write access for the deploy job for contents
> fix(infra): allow-write-contents

- sdks/v4-sdk/src/entities/pool.ts
- sdks/v4-sdk/src/entities/route.test.ts
Simply adding some tests. These are conditions I didn't intentionally build in, but are actually very important, so wanted to clarify that by adding some tests.
> chore(v4-sdk): add important testcases for v4 routes

- sdks/universal-router-sdk/src/index.ts
- sdks/universal-router-sdk/src/utils/constants.ts
- sdks/universal-router-sdk/test/utils/addresses.ts
- sdks/universal-router-sdk/test/utils/constants.test.ts
- This PR aims to expose `UniversalRouterVersion` so that it can be used by consumers
- Unit tests
> fix(universal-router-sdk): expose `UniversalRouterVersion`

- sdks/universal-router-sdk/src/utils/constants.ts
- This PR aims to add string values for the UR versions var
If there are breaking changes, please ensure you bump the major version Bump the major version (by using the title `feat(breaking): ...`), post …
> fix(universal-router-sdk): adds string values for the UR versions var

- sdks/v4-sdk/src/PositionManager.ts
- sdks/v4-sdk/src/index.ts
> fix(v4-sdk): export PositionManager

- sdks/router-sdk/package.json
- yarn.lock
> fix(router-sdk): update v4-sdk to latest

- sdks/universal-router-sdk/src/utils/routerCommands.ts
> feat(universal-router-sdk): add UR position management commands

- sdks/v4-sdk/src/utils/v4Planner.test.ts
- sdks/v4-sdk/src/utils/v4Planner.ts
> fix(v4-sdk): Update take command v4

- sdks/v4-sdk/src/entities/route.ts
> fix(v4-sdk): Fix route encoding v4

- sdks/uniswapx-sdk/integration/test/DutchOrder.spec.ts
> fix(uniswapx-sdk): fund account more

- sdks/universal-router-sdk/package.json
- sdks/universal-router-sdk/src/utils/constants.ts
- yarn.lock
Support worldchain on universal router sdk
No
> feat(universal-router-sdk): support worldchain on universal-router-sdk

- sdks/v4-sdk/src/PositionManager.test.ts
- sdks/v4-sdk/src/PositionManager.ts
> feat(v4-sdk): sweep currency0 and currency1 after addCallParameters

- sdks/v3-sdk/package.json
- yarn.lock
Support astrochain sepolia on v3-sdk
No
> feat(v3-sdk): support astrochain sepolia on v3-sk

- sdks/router-sdk/package.json
- yarn.lock
astrochain sepolia on router-sdk
will test in routing
No
> feat(router-sdk): support astrochain sepolia on router-sdk

- sdks/universal-router-sdk/src/index.ts
> feat(ur-sdk): export migrate params

- sdks/universal-router-sdk/src/utils/constants.ts
Wrong universal router address on astrochain sepolia
will test in swap
No
No
> fix(universal-router-sdk): update astrochain sepolia ur address

- sdks/universal-router-sdk/package.json
- sdks/universal-router-sdk/src/utils/constants.ts
- sdks/v2-sdk/package.json
- yarn.lock
UR 2.0 deployed on astrochain sepolia
No
No
No
> fix(universal-router-sdk): update astrochain sepolia ur 2.0 address

- sdks/universal-router-sdk/src/index.ts
> feat(ur-sdk): export generic command parser

- .github/CODEOWNERS
> chore(codeowners): Update code owners

- sdks/v4-sdk/package.json
> fix(v4-sdk): don't release beta versions of v4

- sdks/v3-sdk/src/nonfungiblePositionManager.test.ts
- sdks/v3-sdk/src/nonfungiblePositionManager.ts
> fix(v3-sdk): fix v3 permit domain separator

- sdks/uniswapx-sdk/src/trade/PriorityOrderTrade.test.ts
- sdks/uniswapx-sdk/src/trade/PriorityOrderTrade.ts
> fix(uniswapx-sdk): add classic amounts to priority order trade

- sdks/sdk-core/src/addresses.ts
Protocol team plan to re-deploy v4 on sepolia tomorrow.
Will test from test web UI.
No
> fix(sdk-core): update v4 addresses once sepolia re-deployed

- sdks/v2-sdk/package.json
- yarn.lock
> fix(v2-sdk): bump sdk-core to get updated v2 sepolia factory address

- sdks/uniswapx-sdk/src/trade/PriorityOrderTrade.test.ts
- sdks/uniswapx-sdk/src/trade/PriorityOrderTrade.ts
> fix(uniswapx-sdk): rename vars to expectedAmountIn/Out for PriorityOrderTrade

- sdks/uniswapx-sdk/src/builder/V3DutchOrderBuilder.test.ts
- sdks/uniswapx-sdk/src/builder/V3DutchOrderBuilder.ts
Static helper function for SDK users to easily get the minimum value of a curve. Useful for getting minOut
> feat(uniswapx-sdk): Helper for minimum output of a curve

- sdks/v4-sdk/src/utils/encodeRouteToPath.ts
> fix(v4-sdk): create a deep copy of pools in v4 encodeRouteToPath

- sdks/v2-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/217
> feat(v2-sdk): bump sdk-core 6.1.1 in v2-sdk

- sdks/v3-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/217 
> feat(v3-sdk): bump sdk-core 6.1.1 in v3-sdk

- sdks/v4-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/217 https://github.com/Uniswap/sdks/pull/233
> feat(v4-sdk): bump sdk-core 6.11 and v3-sdk 3.20.0

- sdks/v4-sdk/package.json
- yarn.lock
> feat(v4-sdk): bump v3-sdk to 3.21.0

- sdks/router-sdk/package.json
- yarn.lock
> feat(router-sdk): bump v4-sdk to 1.15.0 in router-sdk

- sdks/sdk-core/src/addresses.ts
v4 addresses for arbitrum, base and polygon
> feat(sdk-core): v4 addresses for arb base polygon

- sdks/v2-sdk/package.json
- yarn.lock
release https://github.com/Uniswap/sdks/pull/249
> feat(v2-sdk): bump sdk-core to 7.2.0 for arb, base, polygon

- sdks/v4-sdk/package.json
- yarn.lock
release https://github.com/Uniswap/sdks/pull/249
> feat(v4-sdk): bump sdk-core to 7.2.0 for arb, base, polygon

- sdks/universal-router-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/253
> fix(universal-router-sdk): bump router-sdk to 1.19.0

- sdks/v3-sdk/package.json
- yarn.lock
> feat(v3-sdk): bump sdk-core to 7.3.0 for bnb op avax world

- sdks/v4-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/257 https://github.com/Uniswap/sdks/pull/260
> feat(v4-sdk): bump sdk-core to 7.3.0 for bnb op avax world

- sdks/sdk-core/src/addresses.ts
v4 addresses for zora unichain blast
> feat(sdk-core): v4 addresses for zora unichain blast

- sdks/v2-sdk/package.json
- yarn.lock
> feat(v2-sdk): bump sdk-core to 7.3.0 for zora unichain blast

- sdks/sdk-core/src/addresses.ts
> feat(sdk-core): v4 for L1

- sdks/v2-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/269
> feat(v2-sdk): bump sdk-core to 7.5.0 v4 for L1

- sdks/v3-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/266
> feat(v3-sdk): bump sdk-core to 7.4.0 for zora unichain blast

- sdks/v4-sdk/package.json
- yarn.lock
> feat(v4-sdk): v4 for zora unichain blast L1

- sdks/router-sdk/package.json
- yarn.lock
> feat(router-sdk): v4 for zora unichain blast L1

- sdks/uniswapx-sdk/package.json
- sdks/uniswapx-sdk/src/constants.ts
- yarn.lock
Add permit2 mapping for Unichain.
> fix(uniswapx-sdk): Add permit2 map for Unichain

- sdks/universal-router-sdk/package.json
- yarn.lock
> fix(universal-router-sdk): bump router-sdk to 1.21.1

- sdks/router-sdk/src/entities/mixedRoute/route.test.ts
- sdks/router-sdk/src/entities/mixedRoute/route.ts
> fix(router-sdk): fix MixedRoute tokenpath

- sdks/v4-sdk/src/entities/pool.test.ts
- sdks/v4-sdk/src/entities/pool.ts
> fix(v4-sdk): loosen v4 last pool check invariant

- sdks/universal-router-sdk/package.json
- yarn.lock
> feat(universal-router-sdk): bump router-sdk to 1.21.3 and v4-sdk to 1.18.1

- sdks/router-sdk/src/entities/mixedRoute/route.ts
> fix(router-sdk): mixed route last pool v4 check use v4InvolvesToken

- sdks/universal-router-sdk/package.json
- yarn.lock
> fix(universal-router-sdk): bump router-sdk 1.21.4

- sdks/v4-sdk/src/PositionManager.test.ts
- sdks/v4-sdk/src/PositionManager.ts
> fix(v4-sdk): switch back recipient

- sdks/universal-router-sdk/package.json
- yarn.lock
> feat(universalrouter-sdk): bump router-sdk to 1.22.1

- sdks/universal-router-sdk/src/utils/routerTradeAdapter.ts
- sdks/universal-router-sdk/test/uniswapTrades.test.ts
Adds v4 pool support to the RouterTradeAdapter.
Unit tests
No
> feat(universal-router-sdk): Add v4 support to RouterTradeAdapter

- sdks/v4-sdk/src/entities/position.ts
> fix(v4-sdk): use precise liquidity since that is what is being calculated offchain

- sdks/v4-sdk/src/entities/route.ts
V4 ETH/USDC small trade size route has ~5% price impact. we suspect its due to v4-sdk route mid price refactor
I can test in routing
No
> fix(v4-sdk): simplify `midPrice` in `Route` entity (#180)

- sdks/router-sdk/package.json
- sdks/universal-router-sdk/package.json
- yarn.lock
Release https://github.com/Uniswap/sdks/pull/304
Test in routing
No
> fix(router-sdk): bump v4-sdk to 1.19.4

- sdks/universal-router-sdk/package.json
- yarn.lock
Release:
- https://github.com/Uniswap/sdks/pull/305
- https://github.com/Uniswap/sdks/pull/304
No
> fix(universal-router-sdk): bump v4-sdk to 1.19.4 and router-sdk to 1.22.2

- sdks/router-sdk/src/entities/trade.test.ts
- sdks/router-sdk/src/entities/trade.ts
- sdks/v4-sdk/src/entities/pool.test.ts
> fix(router-sdk): add support for inputs requiring wrap or unwraps

- sdks/sdk-core/src/addresses.ts
- sdks/sdk-core/src/chains.ts
- sdks/sdk-core/src/entities/weth9.ts
Add deployed Soneium v2 v3 v4 addresses
Will test on routing
No
> feat(sdk-core): support soneium

- sdks/v2-sdk/package.json
- yarn.lock
Suport Soneium v2 factory
will test in routing
No
> feat(v2-sdk): support soneium

- sdks/v3-sdk/package.json
- yarn.lock
> fix(v3-sdk): support soneium

- sdks/v4-sdk/package.json
- yarn.lock
> feat(v4-sdk): support soneium

- sdks/router-sdk/package.json
- yarn.lock
Support Soneium in router-sdk
No
> feat(router-sdk): support soneium

- sdks/v4-sdk/package.json
- yarn.lock
> fix: update deps in v4-sdk

- sdks/router-sdk/package.json
- yarn.lock
> fix: update deps of router-sdk

- sdks/smart-wallet-sdk/package.json
> feat(smart-wallet-sdk): add release script

- sdks/smart-wallet-sdk/src/utils/callPlanner.test.ts
- sdks/smart-wallet-sdk/src/utils/callPlanner.ts
> fix(smart-wallet-sdk): Call struct ordering

- sdks/v4-sdk/src/PositionManager.test.ts
- sdks/v4-sdk/src/PositionManager.ts
- sdks/v4-sdk/src/entities/position.test.ts
- sdks/v4-sdk/src/entities/position.ts
> fix(v4-sdk): use adjusted liquidity value to bound maximum inputs

- sdks/smart-wallet-sdk/README.md
- sdks/smart-wallet-sdk/src/constants.ts
> feat(smart-wallet-sdk): add deployments for all chains for v0.3.2-audit.2 and v0.2.1-audit.2

- sdks/smart-wallet-sdk/src/constants.ts
> fix(smart-wallet-sdk): deploy on all pectra enabled chains for QA
